**Write a program to create a NumPy 1D-array with 5 elements and perform basic 
operations**


In [5]:
import numpy as np
x=[1,2,3,4,5]
arr=np.array(x)
#1)-(a)
arr_sum=arr+2
print(arr_sum)
#1)-(b)
arr_multiply=arr*3
print(arr_multiply)
#1)-(c)
arr_div=arr/3
print(arr_div)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]


*Questions on Basic NumPy Array*

In [7]:
arr=np.array([1,2,3,6,4,5])
#2)-(a)
arr_rev=arr[::-1]
print(arr_rev)
#2)-(b):1
x=np.array([1,2,3,4,5,1,2,1,1,1])
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_frequent = np.bincount(x).argmax()
indices = np.where(x == most_frequent)[0]
print(most_frequent, indices)



[5 4 6 3 2 1]


In [8]:
#3)
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# a) Accessing the element at the first row and second column
element_1_2 = arr[0][1]
print("Element at (1st row, 2nd column):", element_1_2)
# b) Accessing the element at the third row and first column
element_3_1 = arr[2][0]
print("Element at (3rd row, 1st column):", element_3_1)


Element at (1st row, 2nd column): 20
Element at (3rd row, 1st column): 70


In [21]:
#4)
Karan=np.linspace(10,100,25)
print(Karan)
print("\nDimensions:",Karan.shape)
print("\nTotal elements:",Karan.size)
print("\nData Type of each element:",Karan.dtype)
print("\nTotal Number of bytes consumed:",Karan.itemsize*Karan.size)
print("\nTranspose:\n",Karan.reshape(25))
Karan.T
print("\nYes,we can do the Transpose of this array using T attribute")

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions: (25,)

Total elements: 25

Data Type of each element: float64

Total Number of bytes consumed: 200

Transpose:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Yes,we can do the Transpose of this array using T attribute


In [31]:
ucs420_Karan=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("Mean:",np.mean(ucs420_Karan))
print("\nMedian:",np.median(ucs420_Karan))
print("\nMax:",np.max(ucs420_Karan))
print("\nMin:",np.min(ucs420_Karan))
print("\nUnique elements:",np.unique(ucs420_Karan))
reshaped_ucs420_Karan=ucs420_Karan.reshape(4,3)
print("\n",reshaped_ucs420_Karan)
resized_ucs420_Karan = np.resize(ucs420_Karan, (2, 3))
print("Resized array (2 rows*3 columns):\n",resized_ucs420_Karan)

Mean: 43.333333333333336

Median: 37.5

Max: 90

Min: 10

Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array (2 rows*3 columns):
 [[10 20 30]
 [40 50 60]]
